ignore patterns
rosalindfranklininstitute/rfi-file-monitor pull request #94
Opened 2020-09-22 16:11 UTC by LAShemilt

2020-09-22 16:16 UTC, tschoonj requested changes
Apart from the comment about additional newlines, looks good to me.

Thanks Laura!

2020-09-22 16:16 UTC, tschoonj commented on rfi_file_monitor/applicationwindow.py
> +        self._add_advanced_options_horizontal_separator()
```suggestion
        
        self._add_advanced_options_horizontal_separator()
        
```

Add newlines before and after to improve readability. I will be really happy when we can move the advanced options to its own class and file!

2020-09-23 09:40 UTC, LAShemilt commented
I did not! now I know why my code no longer works :)

2020-09-23 10:54 UTC, tschoonj commented on setup.cfg
> +console_scripts =
This should also not have gone into the commit 😄

2020-09-23 11:02 UTC, tschoonj commented on rfi_file_monitor/utils/__init__.py
> +def get_ignore_patterns_from_string(input: str, defaults=[]) -> List[str]:
Is it possible to combine `get_patterns_from_string` and `get_ignore_patterns_from_string` into a single method?

2020-09-24 10:09 UTC, merged